version: "3.7"
services:
  web:
    #build:
    #  context: .
    image: "networktocode/nautobot:${NAUTOBOT_IMAGE}-py${PYTHON_VER}"
    command: "nautobot-server runserver 0.0.0.0:8080 --insecure"
    depends_on:
    - db
    - redis
    volumes:
      - ./nautobot_config.py:/opt/nautobot/nautobot_config.py
      #- ./uwsgi.ini:/opt/nautobot/uwsgi.ini
    env_file: env/nautobot.env
    restart: "unless-stopped"
    ports:
      - "8080:8080"
    healthcheck:
      interval: "5s"
      timeout: "5s"
      start_period: "5s"
      retries: 3
      test: ["CMD", "nautobot-server", "health_check"]

  worker:
    image: "networktocode/nautobot:${NAUTOBOT_IMAGE}-py${PYTHON_VER}"
      #command: "nautobot-server celery worker --loglevel INFO"
    entrypoint: "sh -c 'nautobot-server celery worker -l $$NAUTOBOT_LOG_LEVEL'"
    depends_on:
      - redis
      - web
    volumes:
      - ./nautobot_config.py:/opt/nautobot/nautobot_config.py
    healthcheck:
      interval: "5s"
      timeout: "5s"
      start_period: "5s"
      retries: 3
      test: ["CMD", "nautobot-server", "health_check"]

    env_file: env/nautobot-dev.env
    restart: "unless-stopped"
    tty: true

  scheduler:
    image: "networktocode/nautobot:${NAUTOBOT_IMAGE}-py${PYTHON_VER}"
    command: "nautobot-server celery beat --loglevel INFO"
    depends_on:
      - redis
      - web
    volumes:
      - ./nautobot_config.py:/opt/nautobot/nautobot_config.py
    restart: "unless-stopped"
    env_file: env/nautobot.env
  
  db:
    image: postgres:15-alpine
    env_file: env/postgres.env
    healthcheck:
      test: "pg_isready -t 2 -d $$POSTGRES_DB -U $$POSTGRES_USER" ## $$ because of docker-compose
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - nautobot-postgres-data:/var/lib/postgresql/data
    restart: "unless-stopped"

  pgadmin:
    image: dpage/pgadmin4
    env_file: env/pgadmin.env
    secrets:
      - pgadmin-secret
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
      - type: bind
        source: pgadmin-secret
        target: /run/secrets/pgadmin-secret
        read_only: true
    ports:
      - "8084:8084"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    command:
    - sh
    - -c # this is to evaluate the $REDIS_PASSWORD from the env
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD ## $$ because of docker-compose
    env_file: env/redis.env
    volumes:
      - nautobot-redis-data:/data
    healthcheck:
      start_period: 20s
      timeout: 3s
      interval: 15s
      test: "timeout 2 redis-cli ping"
    restart: "unless-stopped"


volumes:
  nautobot-postgres-data:
    driver: local
  nautobot-redis-data:
    driver: local

secrets:
  pgadmin-secret:
    #external: true
    file: pgadmin-secret
